preroll:
- name: Thanksgiving/Happy_Thanksgiving_Plex_Pre-roll.mkv
  status: used
  sub_folder: Thanksgiving
- name: New_Years/New_Years_Fireworks_Plex_Pre-roll.mkv
  status: used
  sub_folder: New_Years
- name: New_Years/Happy_New_Year_Plex_Pre-roll.mkv
  status: used
  sub_folder: New_Years
- name: Pride/Netflix_Pride_Colors.mkv
  status: unused
  sub_folder: Pride
- name: Summer/The_Last_Violin_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Summer
- name: Summer/Summer_Vibes_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Summer
- name: Funny/Alamo_Drafthouse_Dont_Talk_Universal_Pre-roll.mkv
  status: used
  sub_folder: Funny
- name: Funny/Forever_Plexing_Pre-roll.mkv
  status: used
  sub_folder: Funny
- name: Funny/No_More_Universal_Pre-roll.mkv
  status: used
  sub_folder: Funny
- name: Funny/IT_Crowd_Anti-Piracy_Universal_Pre-roll.mkv
  status: used
  sub_folder: Funny
- name: Funny/Alamo_Drafthouse_Shush_Universal_Pre-roll.mkv
  status: used
  sub_folder: Funny
- name: Funny/Meme_Vibing_Cat_Pre-roll.mkv
  status: used
  sub_folder: Funny
- name: Funny/Alamo_Drafthouse_No_Talking_Universal_Pre-roll.mkv
  status: used
  sub_folder: Funny
- name: Funny/Shia_Laboeuf_V1_Plex_Pre-roll.mkv
  status: used
  sub_folder: Funny
- name: Funny/Keep_Quiet_PSA_Universal_Pre-roll.mkv
  status: used
  sub_folder: Funny
- name: Funny/Nod_of_Approval_Plex_Pre-roll.mkv
  status: used
  sub_folder: Funny
- name: Retro/VHS_Home_Theater_Plex.mkv
  status: used
  sub_folder: Retro
- name: Retro/VHS_Home_Theater_Plex_V2.mkv
  status: used
  sub_folder: Retro
- name: Retro/80s_VHS_Synthwave_Plex.mkv
  status: used
  sub_folder: Retro
- name: Retro/Retro_VHS_Plex_Pre-roll.mkv
  status: used
  sub_folder: Retro
- name: Retro/Retro_Gaming_Plex_Pre-roll.mkv
  status: used
  sub_folder: Retro
- name: Retro/Miami_1982_Plex_Pre-roll.mkv
  status: used
  sub_folder: Retro
- name: Retro/Discowave_Plex_Pre-roll.mkv
  status: used
  sub_folder: Retro
- name: Retro/Regal_Cinemas__Rollercoaster.mkv
  status: used
  sub_folder: Retro
- name: Retro/VHS_Home_Theater_Plex_V3.mkv
  status: used
  sub_folder: Retro
- name: Retro/Miami_Retrowave_Plex.mkv
  status: used
  sub_folder: Retro
- name: Retro/Synth_Dream_Plex.mkv
  status: used
  sub_folder: Retro
- name: Retro/Our_Feature_Presentation_Blue.mkv
  status: used
  sub_folder: Retro
- name: Retro/Outrun_Plex_Pre-roll.mkv
  status: used
  sub_folder: Retro
- name: Retro/Uber_VHS_Style_Plex_Pre-roll.mkv
  status: used
  sub_folder: Retro
- name: Retro/Cyberpunk_Loading_Plex_Pre-roll.mkv
  status: used
  sub_folder: Retro
- name: Retro/Old_Theater_Film_Intro_Plex_Pre-roll.mkv
  status: used
  sub_folder: Retro
- name: Retro/Retro_CBS_Plex_Pre-roll.mkv
  status: used
  sub_folder: Retro
- name: Retro/80s_Lambo_Plex_Pre-roll.mkv
  status: used
  sub_folder: Retro
- name: Retro/Our_Feature_Presentation.mkv
  status: used
  sub_folder: Retro
- name: Spring/Dancing_Butterflies_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Spring
- name: Spring/Sakura_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Spring
- name: Spring/Happy_Easter_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Spring
- name: Spring/Spring_Brush_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Spring
- name: Spring/Green_Energy_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Spring
- name: Spring/Growing_Grass_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Spring
- name: Spring/Blooming_Flower_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Spring
- name: Spring/Flower_Field_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Spring
- name: Active/Preroll_tgeNUho44b.mkv
  status: unused
  sub_folder: Active
- name: Active/Preroll_Lzk4mcWfq8.mkv
  status: unused
  sub_folder: Active
- name: Active/Preroll_MsiGb9rBMN.mkv
  status: unused
  sub_folder: Active
- name: Xmas/Glitter_Tree_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Snow_Globe_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Christmas_Train_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Glitter_Snow_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Glitter_Merry_Christmas_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Christmas_Tree_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Plex_Snow_Preroll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Christmas_Card_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Santa_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Snowman_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Holiday_Sweater_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Winter_Ice_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Glitter_Trees_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Melting_Snow_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Plex_Magic_Snow_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Christmas_Ornaments_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Christmas_Lights_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Magic_Christmas_Tree_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Merry_Christmas_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Snowflakes_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Magical_Reindeer_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Winter_Snow_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Xmas/Winter_Forest_Lofi_Plex_Pre-roll.mkv
  status: used
  sub_folder: Xmas
- name: Normal/Splash_Cartoon_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Glitch_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/TV_Glitch_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Neon_City_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Paint_Splash_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Fallout_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Neon_Icon_Sign_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Explosion_Reveal_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/plex_apocalypse_2022.mkv
  status: used
  sub_folder: Normal
- name: Normal/Numbers_Glitch_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Colorful_Swirls_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Cartoon_Ink_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Neon_Storm_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Pop_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Ribbon_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Abstract_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Calming_Neon_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Particles_Explosion_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Glitch_Style_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Glitch_Tape_Plex.mkv
  status: used
  sub_folder: Normal
- name: Normal/Colorful_Particles_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Fallout_4_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Sci-Fi_Trails_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Neon_Sign_Reflection_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/TV_Intro_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Standard_Plex_Pre-roll_with_Chime.mkv
  status: used
  sub_folder: Normal
- name: Normal/Plex_Live_TV_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Race_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Magic_Vortex_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Drums_Movie_Poster_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Developer_Coding_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/plex_ambience_2022.mkv
  status: used
  sub_folder: Normal
- name: Normal/Digital_Glitch_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Cinematic_Cards_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Modern_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Sleek_Short_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/plex_colorwheel_2022.mkv
  status: used
  sub_folder: Normal
- name: Normal/Water_Droplets_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Elegant_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Magic_Island_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Plex_preroll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Blue_Glitch_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Elegant_Light_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Lightning_Distortion_Plex.mkv
  status: used
  sub_folder: Normal
- name: Normal/Sci-Fi_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Vibrant_Plex_Pre-Roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Colorful_Transformation_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Windows_Error_Remix_Plex.mkv
  status: used
  sub_folder: Normal
- name: Normal/Neon_Reflection_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Nebula_Energy_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Colorful_Lights_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Plex_Fire_Preroll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Shape_Filling_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/BTTF_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Dubstep_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Neon_Plex_Movies_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Lens_Flare_Plex.mkv
  status: used
  sub_folder: Normal
- name: Normal/Liquid_Glitch_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Elegant_Short_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Laser_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Netflix_Colorful_Lines_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Colorful_Marbles_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Network_Glitch_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Normal/Netflix_Theater_Plex_Pre-roll.mkv
  status: used
  sub_folder: Normal
- name: Black_History/Black_History_Plex_Pre-roll.mkv
  status: used
  sub_folder: Black_History
- name: Halloween/Halloween_Bats_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Zombieland_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Ghost_Reveal_Plex.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Happy_Halloween_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Plex_Stranger_Things_Preroll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Vault_Scary_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Vampire_Bats_Halloween_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Zombies_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Garage_Screams_Plex_Pre-roll.mkv
  status: used
  sub_folder: Halloween
- name: Halloween/Halloween_Spider_Plex_Pre-roll.mkv
  status: used
  sub_folder: Halloween
- name: Halloween/Blood_Splatter_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Horror_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Bloody_Horror_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Spooky_Halloween_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Halloween
- name: Halloween/Monster_Plex_Pre-roll.mkv
  status: used
  sub_folder: Halloween
- name: Fall/Fall_Fox_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Fall
- name: Fall/Simple_Fall_Plex_Pre-roll.mkv
  status: unused
  sub_folder: Fall
- name: Valentines/Valentines_Flowers_Plex.mkv
  status: used
  sub_folder: Valentines
- name: Valentines/Valentines_Hearts_Plex.mkv
  status: used
  sub_folder: Valentines
- name: Valentines/Cartoon_Valentines_Plex_Pre-roll.mkv
  status: used
  sub_folder: Valentines
- name: "Funny/Don't Talk PSA\uFF1A Danny Trejo (R-rated version) [gwH2691KK_4].mkv"
  status: used
  sub_folder: Funny
- name: Funny/f the police. [YRCmmJZRyJs].mkv
  status: used
  sub_folder: Funny
- name: Funny/William Shatner Loblaws commercial [I3Kh8Pii0p4].mkv
  status: used
  sub_folder: Funny
- name: Funny/Skibidi Preroll 2 [iJSDNoqoa7o].mkv
  status: used
  sub_folder: Funny
- name: Funny/Milwaukee County Transit spot [3kCvvjzMxeo].mkv
  status: used
  sub_folder: Funny
- name: Funny/Leonard Nimoy Beeper Commercial from 1979 [VeaqdM2fP0Y].mkv
  status: used
  sub_folder: Funny
- name: Funny/Wooden Salvatore [9ZTkHYJ3r-Y].mkv
  status: used
  sub_folder: Funny
- name: Funny/Alamo at Home Quiet Zone [cp0Xsta77KE].mkv
  status: used
  sub_folder: Funny
- name: Retro/KAET Station ID (1986) [_EsOSxQV3os].mkv
  status: used
  sub_folder: Retro
- name: Black_History/Black History Month (1999) Bumper - Disney Channel [rc2MzXOr2Xc].mkv
  status: used
  sub_folder: Black_History
- name: Black_History/BET Movies Starz 3  - Bumper -  Feature presentation Intro -  Commercial
    (2000) [lOzIWhJK_kQ].mkv
  status: unused
  sub_folder: Black_History
- name: Black_History/This TV Black History Month Bumper (2018) [5ClnxGYI-Bg].mkv
  status: unused
  sub_folder: Black_History
- name: Black_History/Black History is American History - ABC Celebrates Black History
    Month [XNCoxL_lnZY].mkv
  status: used
  sub_folder: Black_History
- name: Pride/1981 NBC bumper- Our Pride is Showing [8-BdW0uSQ1E].mkv
  status: unused
  sub_folder: Pride
- name: Pride2/Netflix_Pride_Colors.mkv
  status: unused
  sub_folder: Pride2
- name: Pride2/1981 NBC bumper- Our Pride is Showing [8-BdW0uSQ1E].mkv
  status: unused
  sub_folder: Pride2
- name: Funny/Max Headroom - Car Parts.mkv
  status: used
  sub_folder: Funny
- name: Funny/Pepperoni Hug Spot.mkv
  status: used
  sub_folder: Funny
- name: Black_History2/Black_History_Plex_Pre-roll.mkv
  status: used
  sub_folder: Black_History2
- name: Black_History2/Black History is American History - ABC Celebrates Black History
    Month [XNCoxL_lnZY].mkv
  status: used
  sub_folder: Black_History2
- name: Black_History2/BET Movies Starz 3  - Bumper -  Feature presentation Intro
    -  Commercial (2000) [lOzIWhJK_kQ].mkv
  status: used
  sub_folder: Black_History2
- name: Black_History2/Black History Month (1999) Bumper - Disney Channel [rc2MzXOr2Xc].mkv
  status: used
  sub_folder: Black_History2
- name: Black_History2/This TV Black History Month Bumper (2018) [5ClnxGYI-Bg].mkv
  status: unused
  sub_folder: Black_History2
