root:
  settings:
    plex_url: "http://plexurl:32400/"
    plex_token: "Your_X-Plex-Token"
    source_folder: "/media/Pre-roll/prerollMedia"
    destination_folder: "/media/Pre-roll/active"
    log_file: "/media/Pre-roll/log/prerollRandomizer.log"
    state_file: "/media/Pre-roll/config/prerollStatefile.yaml"
    allowed_extensions: [".mkv", ".m4v", ".mp4"]
  config:
    - folder:
        name: "Black_History"
        enabled: true
        exclusive: true
        likely: false
        start_date: "2-1"
        end_date: "2-7"
    - folder:
        name: "Black_History2"
        enabled: true
        exclusive: false
        likely: true
        start_date: "2-8"
        end_date: "2-28"
    - folder:
        name: "Fall"
        enabled: true
        exclusive: false
        likely: true
        start_date: "9-22"
        end_date: "10-15"
    - folder:
        name: "Halloween"
        enabled: true
        exclusive: true
        likely: false
        start_date: "10-01"
        end_date: "10-31"
    - folder:
        name: "New_Years"
        enabled: true
        exclusive: true
        likely: false
        start_date: "1-1"
        end_date: "1-1"
    - folder:
        name: "Normal"
        enabled: true
        exclusive: false
        likely: false
        start_date: null
        end_date: null
    - folder:
        name: "Pride"
        enabled: true
        exclusive: true
        likely: false
        start_date: "6-1"
        end_date: "6-7"
    - folder:
        name: "Pride2"
        enabled: true
        exclusive: false
        likely: true
        start_date: "6-8"
        end_date: "6-30"
    - folder:
        name: "Retro"
        enabled: true
        exclusive: false
        likely: false
        start_date: null
        end_date: null
    - folder:
        name: "Funny"
        enabled: true
        exclusive: false
        likely: false
        start_date: null
        end_date: null
    - folder:
        name: "Spring"
        enabled: true
        exclusive: false
        likely: true
        start_date: "3-20"
        end_date: "4-20"
    - folder:
        name: "Summer"
        enabled: true
        exclusive: false
        likely: true
        start_date: "6-21"
        end_date: "7-21"
    - folder:
        name: "Valentines"
        enabled: true
        exclusive: false
        likely: true
        start_date: "2-01"
        end_date: "2-14"
    - folder:
        name: "Thanksgiving"
        enabled: true
        exclusive: true
        likely: false
        start_date: "11-20"
        end_date: "11-30"
    - folder:
        name: "Xmas"
        enabled: true
        exclusive: true
        likely: false
        start_date: "12-01"
        end_date: "12-31"
